name: run-composite
runs:
  using: composite
  steps:
    - run: |
        echo "var_name=var_value" | tee -a "$GITHUB_ENV"

        echo "in dynamic uses, EOF syntax"
        cat <<EOF
        var_name=${var_name}
        var_name (github mustache)=${{env.var_name}}
        EOF

        echo "in dynamic uses, standard echo syntax"
        echo var_name=${var_name}
        echo "var_name (github mustache)=${{env.var_name}}"
      shell: bash
