name: test

on:
  push:
    tags:
      - "v*\\+test*"
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    name: Testing gh messages
    runs-on: ubuntu-latest
    steps:
      - name: "test gh messages"
        run: |
          echo "::notice title=Notice Title::This is a notice"
          echo "::info title=Info title::This is info"
          echo "::warning title=Warning Title::This is a warning"
          echo "::error title=Error title::This is an error"
