name: Build Package

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [windows-latest]
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # pip install docker pywin32>=302
          pip install pygit2 dulwich scmrepo
      - name: Run
        run: |
          python testing.py
