name: Build Package

on:
  push:
  workflow_dispatch:

# jobs:
#   run:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [macos-latest, windows-latest, ubuntu-latest]
#         # python-version: ["3.8", "3.9", "3.10"]
#         python-version: ["3.8"]
#       fail-fast: true

#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip setuptools wheel
#           pip install docker
#       - name: Run
#         run: |
#           python testing.py
#

jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # The keys are configured as recommended in webfactory/ssh-agent README - with
      # repo name given as the comment. Not sure it matters, but DEPLOY_KEY_2 is the
      # one needed by DVC pull
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.SECRET_KEY_1 }}
            ${{ secrets.SECRET_KEY_2 }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install "dvc[s3]"

      - run: dvc get -v https://github.com/dtrifiro/gh-actions-testing ssh.py
