name: Reusable workflow
on:
  workflow_call:
    inputs:
      example:
        description: "example input"
        type: string
        required: false
        default: "default value"
      conditional:
        description: "conditional input"
        type: boolean
        required: false
        default: true
      runner:
        description: "runner label"
        type: string
        required: false
        default: "ubuntu-latest"
      optional-var:
        description: "Optional variable"
        type: string
        required: false
        default:

jobs:
  job1:
    name: job1
    runs-on: ${{inputs.runner}}
    timeout-minutes: 2

    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Print inputs values
        run: |
          echo ${{inputs.example}}

      - name: Print conditional inputs values
        if: ${{inputs.conditional}}
        run: |
          echo "conditional is true"

      - name: Print optional value
        run: |
          echo optional ${{ inputs.optional-var || 'diocane'}}
